# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddc3c7920adc15a5f18654c4a520cea6c484214b36312131b85370283bd2dcdf892ac8f47c25d3e1817635e967435ac0416073fb505feddb2f25bbdb89568f2

test:
  secret_key_base: 5b9a4acd9829097b0f7801952df966bf64faa0c9201c4ec145fd28d0c72b754855c49e40a2f8fdb7e2c7146b3fb3ed8265419e71e1f4bd7ad3981919effe4847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
